sonar.projectKey=jooservices_wordpress-sdk
sonar.organization=jooservices
sonar.sources=src
sonar.tests=tests
sonar.php.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/.github/**,vendor/**,coverage/**,build/**
