#!/bin/sh

set -eu

compose='tools/ci/docker-compose'

consumer_dir="$(mktemp -d /tmp/wordpress-sdk-consumer.XXXXXX)"

cleanup() {
    rm -rf "${consumer_dir}"
}

trap cleanup EXIT INT TERM

${compose} run --rm --no-deps \
    --volume "${consumer_dir}:/consumer" \
    --workdir /consumer \
    php composer init --name=jooservices/wordpress-sdk-consumer --no-interaction

${compose} run --rm --no-deps \
    --volume "${consumer_dir}:/consumer" \
    --workdir /consumer \
    php composer config repositories.wordpress-sdk path /app

${compose} run --rm --no-deps \
    --volume "${consumer_dir}:/consumer" \
    --workdir /consumer \
    php composer require jooservices/wordpress-sdk:@dev --no-interaction --prefer-dist

${compose} run --rm --no-deps \
    --volume "${consumer_dir}:/consumer" \
    --workdir /consumer \
    php php -r 'require "vendor/autoload.php"; $config = new JOOservices\WordPress\Sdk\Config("https://example.test"); if ($config->baseUrl !== "https://example.test/wp-json/") { throw new RuntimeException("SDK smoke test failed."); }'
